# Codecov configuration for DALI Center Integration
# https://docs.codecov.com/docs/codecov-yaml

codecov:
  require_ci_to_pass: true

coverage:
  status:
    project:
      default:
        # Require 80% coverage for the entire project
        target: 80%
        threshold: 5%
        informational: false
    
    patch:
      default:
        # Require 70% coverage for new code changes
        target: 70%
        threshold: 10%
        informational: false

  precision: 2
  round: down
  range: "70...100"

comment:
  layout: "header,files,footer"
  behavior: default
  require_changes: false

ignore:
  - "tests/*"
  - "docs/*"
  - "venv/*"
  - "**/__pycache__/*"
  - "**/*.pyc"
  - "**/test_*.py"
  - "setup.py"
  - "conftest.py"

flag_management:
  default_rules:
    statuses:
      - name_prefix: unittests
        type: project
        target: 80% 