name: Bug Report
description: Create a report to help us improve
title: "[Bug]: "
labels: ["bug"]
body:
  - type: input
    id: version
    attributes:
      label: Version
      placeholder: ex. 0.1.0
    validations:
      required: true
  - type: input
    id: ha-version
    attributes:
      label: Home Assistant Version
      placeholder: ex. 2024.1.0
    validations:
      required: true
  - type: dropdown
    id: installation-type
    attributes:
      label: Home Assistant Installation Type
      description: How is your Home Assistant installed?
      options:
        - Home Assistant Operating System (HAOS)
        - Home Assistant Container
        - Home Assistant Core
        - Home Assistant Supervised
        - Other
    validations:
      required: true
  - type: textarea
    id: what-happened
    attributes:
      label: What happened?
      placeholder: Describe the bug
    validations:
      required: true
  - type: textarea
    id: steps
    attributes:
      label: Steps to Reproduce
      placeholder: |
        1. Go to '...'
        2. Click on '....'
        3. See error
    validations:
      required: true
  - type: textarea
    id: logs
    attributes:
      label: Logs
      description: |
        Please provide relevant log messages to help troubleshoot the issue.
        
        **How to get logs:**
        1. Go to Settings → System → Logs
        2. Copy relevant log entries
        3. Paste them below or attach as a file
        
        **Tip:** For large logs, download `/config/home-assistant.log` via Samba/SSH
      placeholder: Paste your log entries here...
      render: shell 