name: Bug Report
description: Create a report to help us improve
title: "[Bug]: "
labels: ["bug"]
body:
  - type: input
    id: version
    attributes:
      label: Version
      placeholder: ex. 0.1.0
    validations:
      required: true
  - type: input
    id: ha-version
    attributes:
      label: Home Assistant Version
      placeholder: ex. 2024.1.0
    validations:
      required: true
  - type: dropdown
    id: installation-type
    attributes:
      label: Home Assistant Installation Type
      options:
        - Home Assistant Operating System (HAOS)
        - Home Assistant Container
        - Other
    validations:
      required: true
  - type: textarea
    id: what-happened
    attributes:
      label: What happened?
      placeholder: Describe the bug
    validations:
      required: true
  - type: textarea
    id: steps
    attributes:
      label: Steps to Reproduce
      placeholder: |
        1. Go to '...'
        2. Click on '....'
        3. See error
    validations:
      required: true
  - type: markdown
    attributes:
      value: |
        ### Providing Logs

        **For most bugs, standard logs are sufficient.** Only enable debug logging if the issue is complex or we specifically request it.

        #### How to Export Logs:
        1. **Via Home Assistant UI**: 
            - Go to Settings → System → Logs
            - Click "Load Full Home Assistant Log"
            - Use the download button to export logs
        2. **Via File System**: Access `/config/home-assistant.log` directly

        #### Enable Debug Logging (Only if needed):
        If debug logging is required, add this to your `configuration.yaml`:

        ```yaml
        logger:
          default: warning
          logs:
            custom_components.dali_center: debug
            paho: debug
        ```

        Then restart Home Assistant and reproduce the issue.

  - type: textarea
    id: logs
    attributes:
      label: Logs
      placeholder: |
        Please provide relevant log messages here.

        Please include the full error traceback if available.
      render: shell
