name: Bug Report
description: Create a report to help us improve
title: "[Bug]: "
labels: ["bug"]
body:
  - type: input
    id: version
    attributes:
      label: Version
      placeholder: ex. 0.1.0
    validations:
      required: true
  - type: input
    id: ha-version
    attributes:
      label: Home Assistant Version
      placeholder: ex. 2024.1.0
    validations:
      required: true
  - type: dropdown
    id: installation-type
    attributes:
      label: Home Assistant Installation Type
      options:
        - Home Assistant Operating System (HAOS)
        - Home Assistant Container
        - Home Assistant Core
        - Home Assistant Supervised
        - Other
    validations:
      required: true
  - type: textarea
    id: what-happened
    attributes:
      label: What happened?
      placeholder: Describe the bug
    validations:
      required: true
  - type: textarea
    id: steps
    attributes:
      label: Steps to Reproduce
      placeholder: |
        1. Go to '...'
        2. Click on '....'
        3. See error
    validations:
      required: true
  - type: textarea
    id: logs
    attributes:
      label: Logs
      placeholder: |
        Please provide relevant log messages here.
        
        You can find logs in Settings → System → Logs or check `/config/home-assistant.log`
      render: shell 