name: Release

on:
  release:
    types: [ "published" ]
  workflow_dispatch:

permissions:
  contents: write

jobs:
  release-zip:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: ZIP Component Dir
        run: |
          cd ${{ github.workspace }}/custom_components/dali_center
          zip -r dali_center.zip ./

      - name: Upload zip to release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: ${{ github.workspace }}/custom_components/dali_center/dali_center.zip
          asset_name: dali_center.zip
          tag: ${{ github.ref }}
          overwrite: true
