name: Run Tests

on:
  push:
    # branches: [ main ]
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the repository
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pytest homeassistant paho-mqtt pytest-asyncio

      - name: Run tests
        run: |
          pytest -v

      # - name: Upload test coverage report
      #   if: success()
      #   run: |
      #     pip install pytest-cov
      #     pytest --cov=custom_components/dali_center --cov-report=xml

      # - name: Upload coverage report to Codecov
      #   if: success()
      #   uses: codecov/codecov-action@v3
      #   with:
      #     file: ./coverage.xml
      #     fail_ci_if_error: false
